# Generated by Django 3.2.3 on 2021-05-23 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Bid',
        ),
    ]
